default:
  tags:
    - logm

image: maven:3.9-amazoncorretto-21-debian #maven:3.8.5-openjdk-18

variables:
  MAVEN_CLI_OPTS: "-s $MAVEN_SETTINGS_XML --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=50"
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_CPU_LIMIT: "2"
  KUBERNETES_MEMORY_REQUEST: "4Gi"
  KUBERNETES_MEMORY_LIMIT: "8Gi"
  VERSION: ""

cache:
  key: logm-ng
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - snapshot
  - sonarqube



build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile -pl logm-batch

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS org.jacoco:jacoco-maven-plugin:prepare-agent verify



snapshot:
  stage: snapshot
  before_script:
    - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - sha1=${CI_COMMIT_SHORT_SHA}
    - VERSION="${VERSION}_${sha1}_amessk"
    - echo "New version with SHA1:"
    - echo $VERSION
  script:
    - mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$VERSION
    - mvn $MAVEN_CLI_OPTS clean package jib:build -Dmaven.test.skip -Djib.from.auth.username=${MAVEN_REPO_USER} -Djib.from.auth.password=${MAVEN_REPO_PASS} -Djib.to.auth.username=${MAVEN_REPO_USER} -Djib.to.auth.password=${MAVEN_REPO_PASS}

  when: manual
  only:
    - test-abdellah


sonarqube:
  stage: sonarqube
  script:
    - mvn $MAVEN_CLI_OPTS test-compile sonar:sonar -DVERSION=${CI_COMMIT_SHORT_SHA} -Dsonar.branch.name=${CI_COMMIT_BRANCH} -Dsonar.projectKey=com.carrefour.fr.logm:logm-parent -Dsonar.login=a71382dbd2e6d0fc3194002d9ec8f0f0f8e7044b -Dsonar.host.url=https://sonar-enterprise.agilefabric.fr.carrefour.com
  except:
    - tags
    - schedules
